const WEATHER_TAGS = ["clear", "cloudy", "rainy", "foggy", "snowy", "stormy"];
const TEMPERATURE_TAGS = ["cold", "cool", "mild", "warm", "hot"];
const MOOD_TAGS = [
  "relaxed",
  "lonely",
  "healing",
  "excited",
  "nostalgic",
  "sad",
  "gloomy",
  "romantic",
  "tense",
];
const ATMOSPHERE_TAGS = [
  "urban",
  "rural",
  "interior",
  "road",
  "coastal",
  "wilderness",
  "noir",
  "mystery",
  "dreamlike",
  "surreal",
  "period",
  "intimate",
  "grand",
  "gritty",
  "cozy",
];

const MOVIE_LIBRARY = [
  {
    tmdbId: 843,
    title: "In the Mood for Love",
    weatherTags: ["rainy", "cloudy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["lonely", "romantic", "nostalgic"],
    atmosphereTags: ["urban", "interior", "period", "intimate"],
  },
  {
    tmdbId: 872,
    title: "Singin' in the Rain",
    weatherTags: ["rainy", "clear"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["relaxed", "excited", "romantic"],
    atmosphereTags: ["urban", "period", "grand", "cozy"],
  },
  {
    tmdbId: 38,
    title: "Eternal Sunshine of the Spotless Mind",
    weatherTags: ["snowy", "cloudy"],
    temperatureTags: ["cold", "cool"],
    moodTags: ["sad", "romantic", "lonely"],
    atmosphereTags: ["coastal", "dreamlike", "surreal", "intimate"],
  },
  {
    tmdbId: 496243,
    title: "Parasite",
    weatherTags: ["rainy", "stormy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["tense", "gloomy"],
    atmosphereTags: ["urban", "interior", "gritty", "noir"],
  },
  {
    tmdbId: 129,
    title: "Spirited Away",
    weatherTags: ["foggy", "rainy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["healing", "lonely", "excited"],
    atmosphereTags: ["dreamlike", "surreal", "cozy", "grand"],
  },
  {
    tmdbId: 4935,
    title: "Howl's Moving Castle",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["healing", "romantic", "excited"],
    atmosphereTags: ["dreamlike", "cozy", "grand", "surreal"],
  },
  {
    tmdbId: 150540,
    title: "Inside Out",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["healing", "sad", "relaxed"],
    atmosphereTags: ["interior", "dreamlike", "cozy", "surreal"],
  },
  {
    tmdbId: 508442,
    title: "Soul",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["healing", "nostalgic", "lonely"],
    atmosphereTags: ["urban", "dreamlike", "cozy", "surreal"],
  },
  {
    tmdbId: 354912,
    title: "Coco",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["healing", "nostalgic", "sad"],
    atmosphereTags: ["rural", "period", "grand", "cozy"],
  },
  {
    tmdbId: 194,
    title: "Amelie",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["relaxed", "romantic", "healing"],
    atmosphereTags: ["urban", "cozy", "dreamlike", "intimate"],
  },
  {
    tmdbId: 120467,
    title: "The Grand Budapest Hotel",
    weatherTags: ["snowy", "clear"],
    temperatureTags: ["cold", "cool"],
    moodTags: ["relaxed", "nostalgic", "excited"],
    atmosphereTags: ["period", "grand", "cozy", "surreal"],
  },
  {
    tmdbId: 13,
    title: "Forrest Gump",
    weatherTags: ["clear", "rainy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["healing", "nostalgic", "sad"],
    atmosphereTags: ["road", "rural", "period", "cozy"],
  },
  {
    tmdbId: 637,
    title: "Life Is Beautiful",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["mild", "cool"],
    moodTags: ["sad", "healing", "romantic"],
    atmosphereTags: ["period", "intimate", "cozy", "gritty"],
  },
  {
    tmdbId: 424,
    title: "Schindler's List",
    weatherTags: ["cloudy", "snowy"],
    temperatureTags: ["cold", "cool"],
    moodTags: ["sad", "gloomy", "tense"],
    atmosphereTags: ["period", "gritty", "interior", "grand"],
  },
  {
    tmdbId: 12477,
    title: "Grave of the Fireflies",
    weatherTags: ["cloudy", "rainy"],
    temperatureTags: ["hot", "warm"],
    moodTags: ["sad", "gloomy", "lonely"],
    atmosphereTags: ["rural", "period", "gritty", "intimate"],
  },
  {
    tmdbId: 376867,
    title: "Moonlight",
    weatherTags: ["clear", "rainy"],
    temperatureTags: ["warm", "hot"],
    moodTags: ["lonely", "sad", "healing"],
    atmosphereTags: ["coastal", "urban", "intimate", "gritty"],
  },
  {
    tmdbId: 264644,
    title: "Room",
    weatherTags: ["cloudy", "rainy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["tense", "sad", "healing"],
    atmosphereTags: ["interior", "intimate", "gritty", "cozy"],
  },
  {
    tmdbId: 807,
    title: "Se7en",
    weatherTags: ["rainy", "cloudy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["gloomy", "tense"],
    atmosphereTags: ["urban", "noir", "mystery", "gritty"],
  },
  {
    tmdbId: 146233,
    title: "Prisoners",
    weatherTags: ["rainy", "snowy"],
    temperatureTags: ["cold", "cool"],
    moodTags: ["tense", "gloomy", "sad"],
    atmosphereTags: ["rural", "mystery", "gritty", "interior"],
  },
  {
    tmdbId: 210577,
    title: "Gone Girl",
    weatherTags: ["cloudy", "stormy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["tense", "gloomy"],
    atmosphereTags: ["urban", "interior", "mystery", "noir"],
  },
  {
    tmdbId: 745,
    title: "The Sixth Sense",
    weatherTags: ["foggy", "cloudy"],
    temperatureTags: ["cool", "cold"],
    moodTags: ["tense", "gloomy", "sad"],
    atmosphereTags: ["interior", "mystery", "noir", "intimate"],
  },
  {
    tmdbId: 629,
    title: "The Usual Suspects",
    weatherTags: ["foggy", "cloudy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["tense", "gloomy"],
    atmosphereTags: ["noir", "mystery", "interior", "urban"],
  },
  {
    tmdbId: 567,
    title: "Rear Window",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["warm", "hot"],
    moodTags: ["tense", "romantic"],
    atmosphereTags: ["urban", "interior", "mystery", "intimate"],
  },
  {
    tmdbId: 78,
    title: "Blade Runner",
    weatherTags: ["rainy", "foggy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["lonely", "gloomy", "tense"],
    atmosphereTags: ["urban", "noir", "dreamlike", "gritty"],
  },
  {
    tmdbId: 335984,
    title: "Blade Runner 2049",
    weatherTags: ["foggy", "snowy"],
    temperatureTags: ["cold", "cool"],
    moodTags: ["lonely", "gloomy", "tense"],
    atmosphereTags: ["urban", "wilderness", "dreamlike", "grand"],
  },
  {
    tmdbId: 1091,
    title: "The Thing",
    weatherTags: ["snowy", "stormy"],
    temperatureTags: ["cold"],
    moodTags: ["tense", "gloomy"],
    atmosphereTags: ["wilderness", "interior", "mystery", "gritty"],
  },
  {
    tmdbId: 694,
    title: "The Shining",
    weatherTags: ["snowy", "foggy"],
    temperatureTags: ["cold"],
    moodTags: ["tense", "gloomy", "lonely"],
    atmosphereTags: ["interior", "wilderness", "surreal", "gritty"],
  },
  {
    tmdbId: 348,
    title: "Alien",
    weatherTags: ["stormy", "foggy"],
    temperatureTags: ["cold", "cool"],
    moodTags: ["tense", "gloomy"],
    atmosphereTags: ["interior", "mystery", "gritty", "grand"],
  },
  {
    tmdbId: 603,
    title: "The Matrix",
    weatherTags: ["rainy", "stormy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["excited", "tense", "gloomy"],
    atmosphereTags: ["urban", "surreal", "noir", "grand"],
  },
  {
    tmdbId: 27205,
    title: "Inception",
    weatherTags: ["foggy", "stormy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["excited", "tense", "gloomy"],
    atmosphereTags: ["urban", "dreamlike", "surreal", "grand"],
  },
  {
    tmdbId: 157336,
    title: "Interstellar",
    weatherTags: ["clear", "stormy"],
    temperatureTags: ["cold", "hot"],
    moodTags: ["excited", "sad", "healing"],
    atmosphereTags: ["wilderness", "grand", "interior", "cozy"],
  },
  {
    tmdbId: 155,
    title: "The Dark Knight",
    weatherTags: ["stormy", "cloudy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["excited", "tense", "gloomy"],
    atmosphereTags: ["urban", "noir", "grand", "gritty"],
  },
  {
    tmdbId: 24428,
    title: "The Avengers",
    weatherTags: ["clear", "stormy"],
    temperatureTags: ["warm", "mild"],
    moodTags: ["excited", "relaxed"],
    atmosphereTags: ["urban", "grand", "cozy", "road"],
  },
  {
    tmdbId: 299536,
    title: "Avengers: Infinity War",
    weatherTags: ["stormy", "clear"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["excited", "tense", "sad"],
    atmosphereTags: ["grand", "wilderness", "urban", "gritty"],
  },
  {
    tmdbId: 19995,
    title: "Avatar",
    weatherTags: ["clear", "rainy"],
    temperatureTags: ["warm", "hot"],
    moodTags: ["excited", "romantic", "healing"],
    atmosphereTags: ["wilderness", "grand", "dreamlike", "surreal"],
  },
  {
    tmdbId: 85,
    title: "Raiders of the Lost Ark",
    weatherTags: ["clear", "stormy"],
    temperatureTags: ["warm", "hot"],
    moodTags: ["excited", "relaxed"],
    atmosphereTags: ["road", "wilderness", "grand", "gritty"],
  },
  {
    tmdbId: 105,
    title: "Back to the Future",
    weatherTags: ["clear", "stormy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["excited", "relaxed", "nostalgic"],
    atmosphereTags: ["urban", "road", "period", "cozy"],
  },
  {
    tmdbId: 862,
    title: "Toy Story",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["relaxed", "healing", "nostalgic"],
    atmosphereTags: ["interior", "cozy", "road", "intimate"],
  },
  {
    tmdbId: 585,
    title: "Monsters, Inc.",
    weatherTags: ["clear", "foggy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["relaxed", "healing", "excited"],
    atmosphereTags: ["interior", "cozy", "surreal", "urban"],
  },
  {
    tmdbId: 10681,
    title: "WALL·E",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["hot", "warm"],
    moodTags: ["lonely", "healing", "romantic"],
    atmosphereTags: ["wilderness", "interior", "grand", "cozy"],
  },
  {
    tmdbId: 120,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    weatherTags: ["clear", "foggy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["excited", "healing", "nostalgic"],
    atmosphereTags: ["wilderness", "grand", "cozy", "road"],
  },
  {
    tmdbId: 121,
    title: "The Lord of the Rings: The Two Towers",
    weatherTags: ["stormy", "cloudy"],
    temperatureTags: ["cool", "cold"],
    moodTags: ["excited", "tense", "gloomy"],
    atmosphereTags: ["wilderness", "grand", "gritty", "road"],
  },
  {
    tmdbId: 122,
    title: "The Lord of the Rings: The Return of the King",
    weatherTags: ["clear", "stormy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["excited", "healing", "sad"],
    atmosphereTags: ["wilderness", "grand", "cozy", "gritty"],
  },
  {
    tmdbId: 597,
    title: "Titanic",
    weatherTags: ["stormy", "snowy"],
    temperatureTags: ["cold", "cool"],
    moodTags: ["romantic", "sad", "tense"],
    atmosphereTags: ["coastal", "period", "grand", "intimate"],
  },
  {
    tmdbId: 11036,
    title: "The Notebook",
    weatherTags: ["rainy", "clear"],
    temperatureTags: ["warm", "mild"],
    moodTags: ["romantic", "sad", "nostalgic"],
    atmosphereTags: ["rural", "coastal", "period", "intimate"],
  },
  {
    tmdbId: 313369,
    title: "La La Land",
    weatherTags: ["clear", "rainy"],
    temperatureTags: ["warm", "mild"],
    moodTags: ["romantic", "sad", "nostalgic"],
    atmosphereTags: ["urban", "grand", "dreamlike", "intimate"],
  },
  {
    tmdbId: 858,
    title: "Sleepless in Seattle",
    weatherTags: ["rainy", "cloudy"],
    temperatureTags: ["cool", "mild"],
    moodTags: ["romantic", "lonely", "relaxed"],
    atmosphereTags: ["urban", "coastal", "cozy", "intimate"],
  },
  {
    tmdbId: 37165,
    title: "The Truman Show",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["lonely", "healing", "gloomy"],
    atmosphereTags: ["coastal", "surreal", "cozy", "urban"],
  },
  {
    tmdbId: 98,
    title: "Gladiator",
    weatherTags: ["clear", "stormy"],
    temperatureTags: ["hot", "warm"],
    moodTags: ["excited", "sad", "tense"],
    atmosphereTags: ["grand", "period", "gritty", "wilderness"],
  },
  {
    tmdbId: 28,
    title: "Apocalypse Now",
    weatherTags: ["stormy", "foggy"],
    temperatureTags: ["hot", "warm"],
    moodTags: ["gloomy", "tense"],
    atmosphereTags: ["wilderness", "surreal", "gritty", "grand"],
  },
  {
    tmdbId: 7345,
    title: "There Will Be Blood",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["hot", "warm"],
    moodTags: ["gloomy", "tense", "lonely"],
    atmosphereTags: ["rural", "period", "gritty", "grand"],
  },
  {
    tmdbId: 641,
    title: "Requiem for a Dream",
    weatherTags: ["clear", "cloudy"],
    temperatureTags: ["warm", "hot"],
    moodTags: ["gloomy", "sad", "tense"],
    atmosphereTags: ["urban", "interior", "gritty", "surreal"],
  },
  {
    tmdbId: 419430,
    title: "Get Out",
    weatherTags: ["clear", "foggy"],
    temperatureTags: ["mild", "warm"],
    moodTags: ["tense", "gloomy"],
    atmosphereTags: ["rural", "mystery", "gritty", "surreal"],
  },
  {
    tmdbId: 1124,
    title: "The Prestige",
    weatherTags: ["foggy", "cloudy"],
    temperatureTags: ["cool", "cold"],
    moodTags: ["tense", "gloomy", "nostalgic"],
    atmosphereTags: ["period", "mystery", "interior", "noir"],
  },
];

if (typeof module !== "undefined") {
  module.exports = {
    ATMOSPHERE_TAGS,
    MOVIE_LIBRARY,
    MOOD_TAGS,
    TEMPERATURE_TAGS,
    WEATHER_TAGS,
  };
}

if (typeof globalThis !== "undefined") {
  globalThis.ATMOSPHERE_TAGS = ATMOSPHERE_TAGS;
  globalThis.MOVIE_LIBRARY = MOVIE_LIBRARY;
  globalThis.MOOD_TAGS = MOOD_TAGS;
  globalThis.TEMPERATURE_TAGS = TEMPERATURE_TAGS;
  globalThis.WEATHER_TAGS = WEATHER_TAGS;
}
